sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- 4.3
- stable
before_install:
- npm i -g npm
script:
- npm t
after_success: travis-after-all && npm run semantic-release
env:
  global:
  - secure: ytSSwBMbJXuHYNDQZqMaYbY7d/MsHko8uZ3pXzeZWucRFJd/qStRhZKJV8unNjiMtVVBHXjkpAeWSXAkp04/oml/EmEPdJpAoHBkMvFlOCiZbIeFL4/8Fiw6F6hOQB6lHS+XP1++vm2qDXOCkzs0rlVpnlimTr1hvVb8OkR0l7MWzDdO8vy3Oo8Jb1VsKWWARMFlrXJHpNmwm/UgqHiHhHys3+j0IWqnVZ7FvBJNYIH2oqhgMq3JVrcvsx4ECnmlwoOf6OUz3hmIMAHqRFyQyDZbuQaBpDzQDE3Ya5s4e+thFMgOrBjgTtareLPhhmRyoj0qDFlj62BKCgtkYcmWB6OA0A1J1sJ5lvE1UpzqzEaH1hg9jZus8XotYuow+rVr8XPtugZ9Yh+Bx6I03fZZp5Ucv3kCDstxaHFvNH0jPGz05T8rK5PI/ENBm3KTn63kC16sLDduR4al+nsFBoX5c1fCsdme5s2gzEof1sijE3WQIE4ViP+mclX/mMiAn65+bcYY929YVWaDpp73IZJpirrlkvJ9IK/PZ8zDf1mbd+z32FFRu7eX7s1LHPaR2UzXs/iDxaeQvTLSklM9O4Ak1J9Yy9HXLX8hwr10by9sekwh6Zn7l9V94a3U+oCv5BkXahAt0tRqz6oeDpFgw2YOa9ueSgCGQ57AjD36ITb8EoI=
  - secure: Vs1Ol4Wo8/N10MJ0MoowX4Sq+MaTTuWRnL2TbWDl1Z4wpfEtOsQYd+xh8DU1V/2nqnJujs0WWu84HBoUm5hOV5tXpMrrUSs24bFh6NoImVh1T7F45slgqvNF0hPpuGAVomb6wsg8yIL3iXrUrLYZsQIkS2/zDg71pd/hkEZG7uiS0h9T5TKBJtBsrOwIuLDzzrV4S5j22l+/76ALhenYrTFK+puKvrACy0CYQPMMnDRLR/ajodQ6cDPn7POUJdK21mDYmXtfP9cXPsKEZo8Vmkbe7LbHIyt1UXeKWqe7bz0rUFsGY1A4KO99taGFJNs4KpJHmbOTuPqdwy8lWnXf54MEl8jt7PqA1isZcpj0HyyfhdCR0atC2VyFFvUnOTwGYm8CgK6gFpVvK+yaMQW5SdXH6O/z1XyyTIrfh/mznJVaXcP48GxyjOidCXVJ3iJ/Rff4//mx165Ubaff2AQOYkibUVQTrKxuhmhAot1qm+CB4CKbNnxbcm+aMPUFqkdvmVTP59cyXM5b/TM4dhbT86UZmDZrb7a4jp5sIR0SsitUtEiPS2XPzPQSsUeFXCF8hNS4r7Wb6cM5pZTVLuZ5opbtHioh9lkOjU+LKapBLL/t/l4rZkfq7uBCv+8WQMUd1JsnxRYaFrdNrF2usOlwQOY3J5tzLfF1YoTJ4Vj+TF8=
