sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- 4.3
- stable
before_install:
- npm i -g npm
script:
- npm t
after_success: travis-after-all && npm run semantic-release
env:
  global:
  - secure: ztUjON6jNXk0gyrFyChsYMuxfGwXhwNJKHBJIuL1NyHjQ0WG+fnu09KMh4B6JHKO88H5B847Bgo01XbcNXw0aINh5wq3d9C4dZdAs5iHd3OoubpdmYR+KFcR+oeZFbIQrhdnM5skOsBKtbOqSZ2/A8JV+L3BoryY64W2fiUpKy/+Nvvcdnxi7LOY9yTOq2VQdXKViK8t6DFG6QTnoA21ZmEk/kTuPwsvcyI0TX9DQKXP3EWhL6r/CCf4Q4gR7AUDnN+T/X7ZPRdyIQNb7chzXn2BQ1ex3/HrJHEtwa1niVDD/MsW5FJhaEtLOxU6fOXhuSeabWCcKriHZqAVytfrImnhnCoXGn5ptGz90mNcX/divuD6dH7O6rgF9EjW01eYxREcY7Bgs/ZmYqE7mV3d7MS4C1wiz9/FsTrgMikyfGLWnu5tuaE4ASrb7+1AhM0PybL6AvBf/NWlsRsaodMi0UiNe5bFclmw6rrNeL4DIIImkaCEBUTSSt+KMUoRdL4nem+/ksr94Wz3y+Fn8t0Z0+3dJEjygfj/ijEiH+chdJNJgO15P05DU28HRF+34swaArblllaqoNOmF6qlyi7SwqaNOWSWgoxTwrMhwJo3PDgWBblHFk2f0I4zvS3NKeNlqxrAGxv37gwQL84rppSDVuVqFVApOMyjzbEnyDzt1mU=
  - secure: PAWem/jnT2A6WsqsejVV1zn2a9RdwygukTiV10LGo+dbvbiSz64oGWGM+P2feKY+8rNOWTXYq+hIA9GrfCD6dcL7v40WJMtUCcNUD9N29WZMbBE0YgdzUGnN0kAPdeGEHjd5R5gy02Ds4ujDnjzeibwmEJAm/YWJjiI+8p+8CmfSR4NCg4so2h3nOEEvwOAk06skP/lKyyw1/PAOWGonb305uABruPm5MtcHhXcMMjxAXP80kKGqgpEzmApZDUAfUUnUqaMNKEEqrPYkBrXPawMU/HZbYVp9HVmkjlR0BdQ3LeUH611cVkXtJIWaou4HnP3yYPXRS6aes6gRe29bI+zQI+Yz6HinZuThk19tno9+gfkp+fYwvxAlxD5YUxQz6nFQvMw7HQwPJyTY/d+rVAkikO0THVVzZUT+UXlFyu6vIw2ZBVkV4poEwxE5cqeWa/oAobjVTyGpy7DuERF/qFojKgl0nP3/cCZsdYkIvZ3qb1sDXDR9T+O8z05VZxQd/uWplMJj2mF65hA0agzZ4cRXBYuBEBIgt4He6tOGMXxRvaULvia6sziTDCQd6tqPml0P8sl4ePW4viFXFpuUShtrS3losrBpd6Jk9CNyvYnRiwOLktoX7n2bfdjiIr/VXUZZDcX83t0mkQ5OLfLi/art1Gf40cQDPu9nmobY/7Y=
